export type CategoryRule = {
  name: string;
  color: string;
  keywords: string[];
  authors?: string[];
  /** Extra tags applied when this category wins */
  tags?: string[];
  weight: number;
};

export const CATEGORY_RULES: CategoryRule[] = [
  {
    name: "Video & YouTube",
    color: "#fb7185",
    weight: 12,
    tags: ["video", "youtube"],
    keywords: [
      "youtube",
      "yt ",
      "youtuber",
      "video production",
      "video editing",
      "video edit",
      "video gen",
      "video generation",
      "ai video",
      "generate video",
      "text-to-video",
      "text to video",
      "image-to-video",
      "image to video",
      "veo ",
      "veo3",
      "veo 3",
      "runway",
      "runwayml",
      "pika labs",
      "pika ",
      "sora ",
      "kling",
      "luma ai",
      "dream machine",
      "hailuo",
      "minimax video",
      "wan video",
      "wan2",
      "capcut",
      "premiere pro",
      "after effects",
      "davinci",
      "final cut",
      "ffmpeg",
      "thumbnail",
      "thumbnails",
      "youtube shorts",
      "yt shorts",
      "shortform",
      "short-form",
      "longform video",
      "faceless youtube",
      "faceless channel",
      "youtube channel",
      "youtube algo",
      "youtube algorithm",
      "mrbeast",
      "b-roll",
      "broll",
      "storyboard",
      "scriptwriting",
      "video script",
      "vlog",
      "remotion",
      "elevenlabs",
      "voiceover",
      "voice over",
      "ai avatar",
      "heygen",
      "synthesia",
      "descript",
      "opus clip",
      "opusclip",
      "viggle",
      "comfyui video",
      "animate video",
      "motion graphics",
    ],
    authors: [
      "mrbeast",
      "aliabdaal",
      "justinwelsh",
      "thefuturishere",
      "deedydas",
      "ehuanglu",
    ],
  },
  {
    name: "AI & LLMs",
    color: "#a78bfa",
    weight: 10,
    tags: ["ai", "llm"],
    keywords: [
      "llm",
      "gpt",
      "claude",
      "openai",
      "anthropic",
      "gemini",
      "qwen",
      "grok",
      "deepseek",
      "mistral",
      "llama",
      "chatgpt",
      "language model",
      "fine-tun",
      "fine tun",
      "inference",
      "prompt engineer",
      "rag ",
      " agent",
      "agents",
      "mcp",
      "nano banana",
      "midjourney",
      "stable diffusion",
      "comfyui",
      "unsloth",
      "ollama",
      "vllm",
      "machine learning",
      "artificial intelligence",
      "ai model",
      "ai studio",
      "google ai",
      "ai first",
    ],
    authors: [
      "sama",
      "karpathy",
      "ylecun",
      "demishassabis",
      "gdb",
      "unslothai",
      "alibaba_qwen",
      "deepseek_ai",
      "googledeepmind",
      "openai",
      "anthropicai",
      "xai",
      "spacexai",
    ],
  },
  {
    name: "Coding & Dev Tools",
    color: "#38bdf8",
    weight: 9,
    tags: ["coding", "devtools"],
    keywords: [
      "cursor",
      "vscode",
      "github",
      "typescript",
      "javascript",
      "python",
      "react",
      "next.js",
      "nextjs",
      "nodejs",
      "node.js",
      "devtools",
      "open source",
      "docker",
      "kubernetes",
      "postgres",
      "sqlite",
      "supabase",
      "prisma",
      "tailwind",
      "coding",
      "programmer",
      "software engineer",
      "vibe coding",
      "vibe code",
      "claude code",
      "copilot",
      "windsurf",
      "replit",
      "how to use cursor",
      "best practices for using cursor",
    ],
    authors: [
      "leerob",
      "amasad",
      "t3dotgg",
      "shadcn",
      "levelsio",
      "swyx",
      "bcherny",
      "paraschopra",
      "minchoi",
    ],
  },
  {
    name: "Indie Hacking & Startups",
    color: "#34d399",
    weight: 8,
    tags: ["indie-hacking", "startup"],
    keywords: [
      "indie hack",
      "indiehack",
      "saas",
      "startup",
      "arr",
      "mrr",
      "bootstrapp",
      "side project",
      "product hunt",
      "founder",
      "y combinator",
      "build in public",
      "solopreneur",
      "micro-saas",
      "microsaas",
      "ship fast",
      "launched",
    ],
    authors: [
      "levelsio",
      "gregisenberg",
      "yasser_elsaid_",
      "ernestosoftware",
      "prajwaltomar_",
      "aakashgupta",
      "aaditsh",
      "heynavtoor",
      "noahepstein_",
    ],
  },
  {
    name: "Marketing & Growth",
    color: "#fbbf24",
    weight: 8,
    tags: ["marketing", "growth"],
    keywords: [
      "marketing",
      "growth",
      "tiktok",
      "content creat",
      "viral",
      "seo ",
      "copywriting",
      "ogilvy",
      "advertis",
      "funnel",
      "conversion",
      "organic content",
      "fyp",
    ],
    authors: ["the_adprofessor", "pounddz", "alexhormozi"],
  },
  {
    name: "Design & Creative",
    color: "#f472b6",
    weight: 7,
    tags: ["design", "creative"],
    keywords: [
      "design",
      "ui/ux",
      "ui ux",
      "figma",
      "typography",
      "illustration",
      "prompt in the comment",
      "aesthetic",
      "3d render",
      "blender",
      "logo",
      "branding",
      "framer",
      "web design",
      "banger style",
    ],
    authors: ["kubadesign", "hartdrawss", "dangreenheck", "steveschoger", "techhalla"],
  },
  {
    name: "Business & Money",
    color: "#fb923c",
    weight: 7,
    tags: ["business", "money"],
    keywords: [
      "how to get rich",
      "wealth",
      "invest",
      "pricing",
      "sales ",
      "profit",
      "cashflow",
      "cash flow",
      "naval",
      "leverage",
      "get rich",
    ],
    authors: ["naval", "alexhormozi", "kevinnaughtonjr", "thedankoe"],
  },
  {
    name: "News & Politics",
    color: "#f87171",
    weight: 6,
    tags: ["news", "politics"],
    keywords: [
      "gaza",
      "palestine",
      "palestinian",
      "israel",
      "israeli",
      "netanyahu",
      "trump",
      "biden",
      "genocide",
      "apartheid",
      "politics",
      "election",
      "ceasefire",
      "west bank",
      "media outlets",
    ],
    authors: [
      "dropsitenews",
      "ounkaonx",
      "xisraelexposedx",
      "gazanotice",
      "georgegalloway",
      "tparsi",
      "haqiqatjou",
      "petercronau",
      "deepcutnews",
      "elonmusk",
      "ireallyhateyou",
      "uncommonsince76",
      "villgecrazylady",
      "gabbylovesusa",
    ],
  },
  {
    name: "Faith & Religion",
    color: "#2dd4bf",
    weight: 6,
    tags: ["faith", "islam"],
    keywords: [
      "allah",
      "quran",
      "qurʾān",
      "qur'an",
      "islam",
      "muslim",
      "du'a",
      "dua ",
      "prophet",
      "subhanallah",
      "alhamdulillah",
      "hadith",
      "mosque",
      "sunnah",
      "ramadan",
    ],
    authors: ["salahudeen33", "ijazthetrini", "alghurabaaaaaa"],
  },
];

export type CategorizeMatch = {
  collectionName: string;
  tagNames: string[];
  color: string;
  score: number;
};

function normalize(text: string): string {
  return ` ${text.toLowerCase()} `;
}

export function matchCategories(input: {
  text: string;
  authorUsername: string;
  authorName: string;
}): CategorizeMatch | null {
  const hay = normalize(
    `${input.text}\n${input.authorUsername}\n${input.authorName}`
  );
  const author = input.authorUsername.toLowerCase().replace(/^@/, "");

  let best: CategoryRule | null = null;
  let bestScore = 0;

  for (const rule of CATEGORY_RULES) {
    let score = 0;

    for (const kw of rule.keywords) {
      if (hay.includes(kw.toLowerCase())) score += rule.weight;
    }

    if (rule.authors?.some((a) => a.toLowerCase() === author)) {
      score += rule.weight * 3;
    }

    if (score > bestScore) {
      bestScore = score;
      best = rule;
    }
  }

  if (!best || bestScore <= 0) return null;

  return {
    collectionName: best.name,
    tagNames: best.tags ?? [],
    color: best.color,
    score: bestScore,
  };
}
